In [1]:
# Instalar librerías adicionales si es necesario (ejecutar primero)
!pip install seaborn plotly

# Importaciones estándar (¡importa TensorFlow aquí!)
import tensorflow as tf  # <-- Esta línea es la clave que faltaba
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

# Ahora sí, verifica la GPU (después de importar tf)
print("GPU disponible:", tf.config.list_physical_devices('GPU'))

# Configuración de visualización
plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12

print("Entorno configurado correctamente en Google Colab")

GPU disponible: []
Entorno configurado correctamente en Google Colab


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris  # Para dataset de ejemplo
warnings.filterwarnings('ignore')
plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12
print("Entorno configurado para NumPy y Pandas")

Entorno configurado para NumPy y Pandas


# Fundamentos de NumPy y Pandas
En este notebook, exploramos arrays multidimensionales con NumPy y DataFrames con Pandas usando el dataset Iris.

In [3]:
# Cargar dataset Iris como array NumPy
iris = load_iris()
data = iris.data  # Array de shape (150, 4)
print("Forma del array:", data.shape)
print("Primeras 5 filas:\n", data[:5])

# Ejemplo: Crear array propio
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray ejemplo:\n", arr)
print("Suma de elementos:", np.sum(arr))
print("Media por columna:", np.mean(arr, axis=0))

Forma del array: (150, 4)
Primeras 5 filas:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Array ejemplo:
 [[1 2 3]
 [4 5 6]]
Suma de elementos: 21
Media por columna: [2.5 3.5 4.5]


## Ejercicio 1: Arrays NumPy
- Creamos un array 2D y calculamos suma y media. NumPy es eficiente para operaciones vectorizadas (sin loops).

In [4]:
# Convertir a DataFrame Pandas
df = pd.DataFrame(data, columns=iris.feature_names)
df['target'] = iris.target
print("Primeras 5 filas del DataFrame:\n", df.head())
print("\nEstadísticas descriptivas:\n", df.describe())

# Ejemplo: Filtrar y agrupar
especies = df.groupby('target').mean()
print("\nMedia por especie:\n", especies)

Primeras 5 filas del DataFrame:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  

Estadísticas descriptivas:
        sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
5

## Ejercicio 2: DataFrames Pandas
- Cargamos datos en un DataFrame, exploramos con `head()` y `describe()`, y agrupamos por clases.

## Conclusión
NumPy maneja cálculos numéricos rápidos; Pandas facilita el análisis tabular. Próximo: Visualizaciones.

In [5]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!git config --global user.email "boris.tigre@uees.edu.ec"
!git config --global user.name "Boris Tigre"

# Limpieza
!rm -rf /content/UEES-IA-Semana1-TigreBoris

# Clon
!git clone https://github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris.git /content/UEES-IA-Semana1-TigreBoris
%cd /content/UEES-IA-Semana1-TigreBoris

# Carpetas
!mkdir -p ./02_Laboratorio/notebooks/

# Copia del notebook
!cp "/content/drive/MyDrive/Colab Notebooks/01_Fundamentos_NumPy_Pandas.ipynb" ./02_Laboratorio/notebooks/

# Commit
!git add .
!git commit -m "Añadir notebook de fundamentos"

# Push CON TU TOKEN (¡cambia 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 por el ghp_... que copiaste!)
!git push https://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@github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris.git main

print("¡Subido! Ve a github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris para ver el notebook.")

Mounted at /content/drive
Cloning into '/content/UEES-IA-Semana1-TigreBoris'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 8 (delta 0), reused 5 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (8/8), done.
/content/UEES-IA-Semana1-TigreBoris
[main 6cea58d] Añadir notebook de fundamentos
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite 02_Laboratorio/notebooks/01_Fundamentos_NumPy_Pandas.ipynb (82%)
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 4.46 KiB | 4.46 MiB/s, done.
Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote: 
remote: - GITHUB PUSH PROTECTION
remote:   —————————————————————————————————————————
remote:     Resolve the following violations before pus

In [6]:
from google.colab import drive
from google.colab import auth

# Función para guardar automáticamente en GitHub (corregida para token nuevo)
def save_to_github(notebook_name, commit_message="Actualizar notebook"):
    """
    Guarda el notebook actual en GitHub
    """
    # Conecta Drive
    drive.mount('/content/drive', force_remount=True)

    # Autenticación
    auth.authenticate_user()

    # Config Git
    !git config --global user.email "boris.tigre@uees.edu.ec"
    !git config --global user.name "Boris Tigre"

    # Limpieza y clon
    !rm -rf /content/UEES-IA-Semana1-TigreBoris
    !git clone https://github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris.git /content/UEES-IA-Semana1-TigreBoris
    %cd /content/UEES-IA-Semana1-TigreBoris

    # Carpetas
    !mkdir -p ./02_Laboratorio/notebooks/

    # Copia desde Drive
    !cp "/content/drive/MyDrive/Colab Notebooks/{notebook_name}" ./02_Laboratorio/notebooks/

    # Commit
    !git add .
    !git commit -m "{commit_message}"

    # Push con NUEVO TOKEN (¡cambia TU_NUEVO_TOKEN por el ghp_... nuevo!)
    !git push https://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@github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris.git main

    print(f" {notebook_name} guardado en GitHub")

# Usar al final
save_to_github("01_Fundamentos_NumPy_Pandas.ipynb", "Completar ejercicios de NumPy y Pandas")

Mounted at /content/drive
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Cloning into '/content/UEES-IA-Semana1-TigreBoris'...
fatal: Unable to read current working directory: No such file or directory
[Errno 2] No such file or directory: '/content/UEES-IA-Semana1-TigreBoris'
/content/UEES-IA-Semana1-TigreBoris
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
mkdir: cannot create directory ‘./02_Laboratorio’: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
cp: cannot create regular file './02_Laboratorio/notebooks/': No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
fatal: Unable to read current working directory: No such file or directory
shell-init: error retrieving c