In [ ]:
# Instalar librerías adicionales si es necesario (ejecutar primero)
!pip install seaborn plotly

# Importaciones estándar (¡importa TensorFlow aquí!)
import tensorflow as tf  # <-- Esta línea es la clave que faltaba
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

# Ahora sí, verifica la GPU (después de importar tf)
print("GPU disponible:", tf.config.list_physical_devices('GPU'))

# Configuración de visualización
plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12

print("Entorno configurado correctamente en Google Colab")

GPU disponible: []
Entorno configurado correctamente en Google Colab


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris  # Para dataset de ejemplo
warnings.filterwarnings('ignore')
plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12
print("Entorno configurado para NumPy y Pandas")

Entorno configurado para NumPy y Pandas


# Fundamentos de NumPy y Pandas
En este notebook, exploramos arrays multidimensionales con NumPy y DataFrames con Pandas usando el dataset Iris.

In [ ]:
# Cargar dataset Iris como array NumPy
iris = load_iris()
data = iris.data  # Array de shape (150, 4)
print("Forma del array:", data.shape)
print("Primeras 5 filas:\n", data[:5])

# Ejemplo: Crear array propio
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray ejemplo:\n", arr)
print("Suma de elementos:", np.sum(arr))
print("Media por columna:", np.mean(arr, axis=0))

Forma del array: (150, 4)
Primeras 5 filas:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Array ejemplo:
 [[1 2 3]
 [4 5 6]]
Suma de elementos: 21
Media por columna: [2.5 3.5 4.5]


## Ejercicio 1: Arrays NumPy
- Creamos un array 2D y calculamos suma y media. NumPy es eficiente para operaciones vectorizadas (sin loops).

In [ ]:
# Convertir a DataFrame Pandas
df = pd.DataFrame(data, columns=iris.feature_names)
df['target'] = iris.target
print("Primeras 5 filas del DataFrame:\n", df.head())
print("\nEstadísticas descriptivas:\n", df.describe())

# Ejemplo: Filtrar y agrupar
especies = df.groupby('target').mean()
print("\nMedia por especie:\n", especies)

Primeras 5 filas del DataFrame:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  

Estadísticas descriptivas:
        sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
5

## Ejercicio 2: DataFrames Pandas
- Cargamos datos en un DataFrame, exploramos con `head()` y `describe()`, y agrupamos por clases.

## Conclusión
NumPy maneja cálculos numéricos rápidos; Pandas facilita el análisis tabular. Próximo: Visualizaciones.

In [ ]:
from getpass import getpass
from google.colab import drive
from google.colab import auth
import subprocess  # Ayudante para sustituir el token en Git

# Pide el token de forma segura (pégalo aquí – no se ve)
token = getpass("Pega tu token de GitHub aquí (no se verá): ")

# Conecta Drive y auth
drive.mount('/content/drive', force_remount=True)
auth.authenticate_user()

!git config --global user.email "boris.tigre@uees.edu.ec"
!git config --global user.name "Boris Tigre"

# Limpieza y clon
!rm -rf /content/UEES-IA-Semana1-TigreBoris
!git clone https://github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris.git /content/UEES-IA-Semana1-TigreBoris
%cd /content/UEES-IA-Semana1-TigreBoris

# Carpetas
!mkdir -p ./02_Laboratorio/notebooks/

# Copia desde Drive
!cp "/content/drive/MyDrive/Colab Notebooks/01_Fundamentos_NumPy_Pandas.ipynb" ./02_Laboratorio/notebooks/

# Commit
!git add .
!git commit -m "Añadir notebook de fundamentos"

# TRUCO: Sustituye el token correctamente en el comando de Git (sin "{token}")
subprocess.run(["git", "remote", "set-url", "origin", f"https://{token}@github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris.git"])

# Push (ahora con el token sustituido, no falla)
!git push origin main

print("¡Subido! Ve a github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris para ver el notebook.")

Pega tu token de GitHub aquí (no se verá): ··········
Mounted at /content/drive
Cloning into '/content/UEES-IA-Semana1-TigreBoris'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 28 (delta 4), reused 24 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (28/28), 9.47 KiB | 387.00 KiB/s, done.
Resolving deltas: 100% (4/4), done.
/content/UEES-IA-Semana1-TigreBoris
[main 9ed8623] Añadir notebook de fundamentos
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 804 bytes | 804.00 KiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris.git
   992b375..9ed8623  main -> main


In [ ]:
from google.colab import drive

# Conecta Drive (para encontrar el notebook)
drive.mount('/content/drive', force_remount=True)

# Asegúrate de estar en el repo (carpetas ya existen)
%cd /content/UEES-IA-Semana1-TigreBoris

# Función para guardar automáticamente en GitHub (corregida para Drive)
def save_to_github(notebook_name, commit_message="Actualizar notebook"):
    """
    Guarda el notebook actual en GitHub
    """
    # Copia DESDE DRIVE (el lugar correcto, con f-string para sustituir el nombre)
    !cp "/content/drive/MyDrive/Colab Notebooks/{notebook_name}" ./02_Laboratorio/notebooks/
    !git add .
    !git commit -m "{commit_message}"
    !git push origin main
    print(f" {notebook_name} guardado en GitHub")

# Usar al final de cada sesión de trabajo
save_to_github("01_Fundamentos_NumPy_Pandas.ipynb", "Completar ejercicios de NumPy y Pandas")

Mounted at /content/drive
/content/UEES-IA-Semana1-TigreBoris
[main d4f7f6f] Completar ejercicios de NumPy y Pandas
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite 02_Laboratorio/notebooks/01_Fundamentos_NumPy_Pandas.ipynb (85%)
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 2.25 KiB | 2.25 MiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/boristigre-uees/UEES-IA-Semana1-TigreBoris.git
   9ed8623..d4f7f6f  main -> main
 01_Fundamentos_NumPy_Pandas.ipynb guardado en GitHub
